### ISSUE TITLE
Fails on simple git-tag project

### ISSUE THREAD

**Issue by hipstersmoothie** [terradatum/auto-action#117]
**Describe the bug**

trying to setup a minimal auto example. build failed because `npm ci` is called somewhere i think

https://github.com/hipstersmoothie/auto-minimal-github-actions/runs/690482147?check_suite_focus=true

**Expected behavior**

Should handle non-npm projects

**Comment by hipstersmoothie** [comment]
It seems like the code should fallback to non-npm auto if the `npm ci` fails...

**Comment by rbellamy** [comment]
Do me a favor and set `ACTIONS_STEP_DEBUG` to `true` and re-run? I'm unclear why it's NOT falling back to a non-npm auto executable.

https://github.com/actions/toolkit/blob/master/docs/action-debugging.md

**Comment by rbellamy** [comment]
I think I understand what's happening - even though it's not an npm project, I think npx IS found in the path. That's what I'm using to detect whether I should use `npx auto` or an executable version of auto.

https://github.com/terradatum/auto-action/blob/77cc30d81686465e986ab2ef3f879143a4d2fb12/src/auto-command-manager.ts#L604

I'm open to suggestions on what I should use for detecting whether I should be running `npx auto` or just plain `auto`.

**Comment by hipstersmoothie** [comment]
I think a `fs.existsSync('package.json')` would probably accomplish this behavior. 

btw I've been working on a plugin that automates publishing github actions. It keeps `v1` type branches and has options that fix commiting node_modules and dist. Let me know what you think!

https://github.com/intuit/auto/pull/1238

**Comment by rbellamy** [comment]
I like the plugin and will use it once you release it.
